# Read the Docs configuration file
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

# Use MkDocs instead of Sphinx
mkdocs:
  configuration: mkdocs.yml

# Install Python dependencies
python:
  install:
    - requirements: docs/requirements.txt
