{% set name = "omnipkg" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: REDACTED
  
build:
  number: 0
  noarch: python
  script: "python -m pip install . --no-deps --no-build-isolation -vv"
  entry_points:
    - omnipkg = omnipkg.cli:main
    - 8pkg = omnipkg.cli:main

requirements:
  host:
    - python >=3.7,<3.15
    - pip
    - setuptools >=61.0
  run:
    - python >=3.7,<3.15
    # Conditional logic for packaging based on Python version
    - packaging >=23.0  # [py>=310]
    - packaging >=21.0,<22.0  # [py<310]
    - requests >=2.20
    - authlib >=1.6.5
    - filelock >=3.9
    - tomli  # [py<311]
    # Conditional logic for safety
    - safety >=3.0  # [py>=310 and py<314]
    - aiohttp >=3.13.1
    # Conditional logic for pip-audit
    - pip-audit >=2.6.0  # [py>=314]
    - uv >=0.9.5

test:
  imports:
    - omnipkg
  commands:
    - omnipkg --version

about:
  home: https://github.com/1minds3t/omnipkg
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE
  summary: 'The Ultimate Python Dependency Resolver. One environment. Infinite packages. Zero conflicts.'
  description: |
    omnipkg is not just a package manager; it's an intelligent, self-healing runtime
    orchestrator that breaks the fundamental laws of Python environments. It allows
    multiple versions of any package—and even multiple Python interpreters—to
    coexist and hot-swap in a single environment.
    
    This version introduces "Quantum Healing," an AI-driven feature that makes
    the tool self-aware of Python version incompatibilities.
    
    Key Features:
      • **NEW - Quantum Healing:** Automatically detects if a package is incompatible
        with your current Python version. It will then find a compatible Python
        version, adopt it, switch the environment context, and complete the
        installation—all in a single, seamless command.
      
      • **Cross-Interpreter Adoption & Management:** omnipkg can discover, adopt,
        and manage multiple Python interpreters (e.g., 3.9, 3.10, 3.11+) within one
        unified environment, enabling true cross-version testing and development.
        
      • **Live Hot-Swapping:** Dynamically switch between conflicting C-extensions
        (like NumPy/SciPy) or entire Python interpreters mid-script, without
        restarting or using virtualenvs.
        
      • **Auto-Healing & Environment Repair:** Proactively finds and removes corrupted
        installations left by other tools. The `omnipkg run` command detects and
        fixes `ModuleNotFoundError` and version conflicts on the fly.
        
      • **Concurrent Operations:** A high-performance core allows omnipkg to run
        operations across multiple Python versions concurrently, drastically
        accelerating CI/CD pipelines and complex test suites.
    
    omnipkg eliminates the need for managing countless virtualenvs or Docker images,
    providing a single, unified, and intelligent environment for developers and
    data scientists who demand maximum flexibility and speed.
    
  doc_url: https://omnipkg.readthedocs.io/en/latest/
  dev_url: https://github.com/1minds3t/omnipkg

extra:
  recipe-maintainers:
    - 1minds3t
