name: Deploy MkDocs Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-mermaid2-plugin
      
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
